local min, floor = math.min, math.floor
local ilLerp = MATH.ilLerp
local function floorRank(l0, l1, l2, l3, l4, l5, l6)
    local l = {
        l0 <= 10 and Floors[l0 - 1].top or l0,
        l1 <= 10 and Floors[l1 - 1].top or l1,
        l2 <= 10 and Floors[l2 - 1].top or l2,
        l3 <= 10 and Floors[l3 - 1].top or l3,
        l4 <= 10 and Floors[l4 - 1].top or l4,
        l5 <= 10 and Floors[l5 - 1].top or l5,
        l6 <= 10 and Floors[l6 - 1].top or l6,
    }
    assert(#l == 7)
    return function(h) return min(6 * ilLerp(l, h), 5.9999) end
end
local function numberRank(...)
    local l = { ... }
    assert(#l == 7)
    for i = 1, 6 do assert(l[i] <= l[i + 1], "Ranks must be in ascending order") end
    return function(s) return min(6 * ilLerp(l, s), 5.9999) end
end
local function numberRankRev(...)
    local l = TABLE.reverse { ... }
    assert(#l == 7)
    for i = 1, 6 do assert(l[i] <= l[i + 1], "Ranks must be in descending order") end
    return function(s) return min(6 * (1 - ilLerp(l, s)), 5.9999) end
end
local function heightFloor(h)
    for i = 9, 0, -1 do
        if h >= Floors[i].top then
            return "FLOOR " .. (i + 1)
        end
    end
end
local function heightNumber(score)
    return string.format("%.1fm", score)
end
local function issuedScore()
    return "DONE!"
end

---@class Achievement
---@field title? string
---@field ex? true Extended by Zenith Clicker
---@field id? string
---@field name? string
---@field desc? string
---@field quote? string
---@field credit? string
---@field comp? '<' | '>' | fun(newScore, oldScore):boolean
---@field noScore? number
---@field scoreSimp? fun(score):string
---@field scoreFull? fun(score):string
---@field rank? 'floor' | fun(score):number
---@field type? 'competitive' | 'unranked' | 'issued' | 'event'
---@field hide? fun():boolean

---@type Map<Achievement>
Achievements = {
    { title = "General" },
    { -- contender
        id = 'contender',
        name = "Contender",
        desc = [[games played]],
        quote = [["Some day, everyone will remember your name!" - Clicker League Ad]],
        scoreSimp = function(n) return n .. " Games" end,
        rank = numberRank(0, 6, 26, 126, 260, 620, 1260),
        type = 'unranked',
    },
    { -- clicker
        id = 'clicker',
        name = "Clicker",
        desc = [[cards flipped]],
        quote = [[Greater than the sum of its parts?]],
        scoreSimp = function(n) return string.format("%.2fk Flips", n / 1000) end,
        rank = numberRank(0, 6200, 12600, 26e3, 62e3, 126e3, 260e3),
        type = 'unranked',
    },
    { -- elegance
        id = 'elegance',
        name = "Elegance",
        desc = [[quests perfectly passed]],
        quote = [[Path of least resistance.]],
        scoreSimp = function(n) return string.format("%.2fk Quests", n / 1000) end,
        rank = numberRank(0, 1200, 2600, 6200, 12600, 26e3, 62e3),
        type = 'unranked',
    },
    { -- garbage_offensive
        id = 'garbage_offensive',
        name = "Garbage Offensive",
        desc = [[attack sent]],
        quote = [[The act of violence and communication of spirit.]],
        scoreSimp = function(n) return string.format("%.2fk Attack", n / 1000) end,
        rank = numberRank(0, 12600, 26e3, 62e3, 126e3, 260e3, 620e3),
        type = 'unranked',
    },
    { -- tower_climber
        id = 'tower_climber',
        name = "Tower Climber",
        desc = [[meters climbed]],
        quote = [["Have I been here before..?"]],
        scoreSimp = function(h) return string.format("%.2fkm", h / 1000) end,
        rank = numberRank(0, 2600, 6200, 12600, 26e3, 62e3, 260e3),
        type = 'unranked',
    },
    { -- tower_regular
        id = 'tower_regular',
        name = "Tower Regular",
        desc = [[floors climbed]],
        quote = [["I have been here before!"]],
        scoreSimp = function(n) return string.format("%d Floors", n) end,
        rank = numberRank(0, 126, 260, 620, 1260, 2600, 12600),
        type = 'unranked',
    },
    { -- speed_player
        id = 'speed_player',
        name = "Speed Player",
        desc = [[speedruns entered]],
        quote = [[A simple strategy that can overwhelm even the most poised of masters.]],
        scoreSimp = function(n) return n .. " GIGAs" end,
        rank = numberRank(0, 26, 62, 120, 260, 620, 1260),
        type = 'unranked',
        hide = function() return STAT.totalGiga == 0 end,
    },
    { -- plonk
        id = 'plonk',
        name = "Plonk",
        desc = [[Highest altitude within the first 7 quests]],
        quote = [[Pour intention into each flip, and even a single quest can shake the world.]],
        credit = "@Ponies",
        scoreSimp = function(h) return string.format("%.1fm", h) end,
        scoreFull = function(h) return string.format("%.2f m/quest", h / 7) end,
        rank = numberRank(60, 75, 90, 100, 110, 120, 135),
    },
    { -- zenith_explorer
        id = 'zenith_explorer',
        name = "Zenith Explorer",
        desc = [[HFD without any mods]],
        quote = [[Uncover the mysteries of the Zenith Tower.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 6200),
    },
    { -- zenith_explorer_plus
        ex = true,
        id = 'zenith_explorer_plus',
        name = "Zenith Explorer+",
        desc = [[HFD]],
        quote = [[Uncover the mysteries of the Zenith Tower.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 8000),
    },
    { -- clicker_speedrun
        ex = true,
        id = 'clicker_speedrun',
        name = "Clicker Speedrun",
        desc = [[Least time spent completing 40 quests without any mods]],
        quote = [[Supercharged Q40%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.2f quests/s", 40 / time) end,
        rank = numberRankRev(94.2, 72, 55, 42, 33, 26, 20),
    },
    { -- naga_eyes
        id = 'naga_eyes',
        name = "Naga Eyes",
        desc = [[Least time spent completing 40 quests with rMS AS]],
        quote = [[The ancient wisdom that lies behind a serpent's gaze.]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.2f quests/s", 40 / time) end,
        rank = numberRankRev(90, 74, 62, 53, 46, 42, 36),
        hide = function() return GAME.completion.MS == 0 end,
    },
    { -- supercharged
        id = 'supercharged',
        name = "Supercharged",
        desc = [[Highest Back-to-Back chain reached without any mods]],
        quote = [["With this divine power, we'll be unstoppable!" -Mathis, Core Engineer]],
        scoreSimp = function(b2b) return "B2B x" .. b2b end,
        rank = numberRank(0, 20, 40, 65, 90, 120, 180),
    },
    { -- supercharged_plus
        ex = true,
        id = 'supercharged_plus',
        name = "Supercharged+",
        desc = [[Highest Back-to-Back chain reached]],
        quote = [[Supercharged Any%]],
        scoreSimp = function(b2b) return "B2B x" .. b2b end,
        rank = numberRank(0, 20, 40, 65, 90, 120, 180),
    },
    { -- multitasker
        ex = true,
        id = 'multitasker',
        name = "Multitasker",
        desc = [[Highest altitude*modPoints]],
        quote = [[Master doing everything, then master doing everything.]],
        credit = "@Flowerling",
        scoreSimp = function(mmp) return floor(mmp) .. "m·MP" end,
        rank = numberRank(0, 4200, 6200, 9420, 12600, 16200, 26000),
        hide = TRUE,
    },
    { -- effective
        ex = true,
        id = 'effective',
        name = "Effective",
        desc = [[Highest altitude*ZPmul]],
        quote = [[Master doing everything efficiently.]],
        scoreSimp = function(zp) return floor(zp) .. " ZP" end,
        rank = numberRank(0, 2600, 4200, 6200, 10000, 12600, 16200),
        hide = TRUE,
    },
    { -- zenith_speedrun
        id = 'zenith_speedrun',
        name = "Zenith Speedrun",
        desc = [[Reach F10 as fast as possible while retaining GIGASPEED without any mods]],
        quote = [[F10 Giga%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", Floors[9].top / time) end,
        rank = numberRankRev(260, 126, 100, 90, 82.6, 76.2, 62.6),
        hide = function() return STAT.totalGiga == 0 end,
    },
    { -- zenith_speedrun_plus
        ex = true,
        id = 'zenith_speedrun_plus',
        name = "Zenith Speedrun+",
        desc = [[Reach F10 as fast as possible while retaining GIGASPEED]],
        quote = [[F10 Any%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", Floors[9].top / time) end,
        rank = numberRankRev(260, 126, 100, 90, 82.6, 76.2, 56.7),
        hide = function() return STAT.totalGiga == 0 end,
    },
    { -- zenith_challenger
        ex = true,
        id = 'zenith_challenger',
        name = "Zenith Challenger",
        desc = [[Total best altitude with 1 mod enabled]],
        quote = [[Challenge the reality of the Zenith Tower.]],
        credit = "@5han",
        scoreSimp = function(h) return string.format("%.2fkm", h / 1000) end,
        rank = numberRank(0, 14000, 26000, 36000, 42000, 46000, 52600),
        hide = TRUE,
    },
    { -- divine_challenger
        ex = true,
        id = 'divine_challenger',
        name = "Divine Challenger",
        desc = [[Total best altitude with 1 rev mod enabled]],
        quote = [[Expose the darkness of the Zenith Tower.]],
        scoreSimp = function(h) return string.format("%.2fkm", h / 1000) end,
        rank = numberRank(0, 10000, 16000, 20000, 24000, 26000, 30000),
        hide = TRUE,
    },
    { -- zenith_speedrunner
        ex = true,
        id = 'zenith_speedrunner',
        name = "Zenith Speedrunner",
        desc = [[Sum of best GIGASPEED times with each mod]],
        quote = [[F10 All%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(2600, 2000, 1500, 1260, 1100, 1000, 900),
        hide = TRUE,
    },
    { -- divine_speedrunner
        ex = true,
        id = 'divine_speedrunner',
        name = "Divine Speedrunner",
        desc = [[Sum of best GIGASPEED time with each rev mod]],
        quote = [[F10 All+%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(12600, 9420, 8720, 7023, 6200, 3600, 1620),
        hide = TRUE,
    },
    { -- the_spike_of_all_time
        id = 'the_spike_of_all_time',
        name = "The Spike of All Time",
        desc = [[Largest spike sent (excluding Surge)]],
        quote = [[Flashy techniques are a staple amongst the glory-seeking competitive climbers...]],
        scoreSimp = function(spike) return floor(spike) .. " Spike" end,
        rank = numberRank(0, 12, 20, 26, 42, 62, 100),
    },
    { -- the_spike_of_all_time_minus
        ex = true,
        id = 'the_spike_of_all_time_minus',
        name = "The Spike of All Time-",
        desc = [[Largest spike sent without any mods (excluding Surge)]],
        quote = [[...but some climbers prefer to fully rely on their own strength...]],
        scoreSimp = function(spike) return floor(spike) .. " Spike" end,
        rank = numberRank(0, 12, 20, 26, 32, 38, 42),
    },
    { -- clock_out
        ex = true,
        id = 'clock_out',
        name = "Clock Out",
        desc = [[Runs finished right after reaching F10]],
        quote = [["Well, my job here is done."]],
        scoreSimp = function(n) return n == 1 and "1 Shift" or n .. " Shifts" end,
        rank = numberRank(0, 0, 0, 6, 12, 26, 62),
        type = 'unranked',
        hide = TRUE,
    },
    { -- vip_list
        id = 'vip_list',
        name = "VIP List",
        desc = [[Number of daily combos mastered containing any reversed mod]],
        quote = [[Unparalleled luxury for a select few.]],
        scoreSimp = function(day) return day == 1 and "1 Day" or day .. " Days" end,
        rank = numberRank(0, 0, 1, 2, 4, 6, 12),
        type = 'unranked',
        hide = TRUE,
    },

    { title = "Mods" },
    { -- EX
        id = 'EX',
        name = "The Emperor",
        desc = [[HFD with the "Expert Mode" mod]],
        quote = [[A display of power for those willing to bear its burden.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- NH
        id = 'NH',
        name = "Temperance",
        desc = [[HFD with the "No Hold" mod]],
        quote = [[Use each piece as they come and embrace the natural flow of stacking.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- MS
        id = 'MS',
        name = "Wheel of Fortune",
        desc = [[HFD with the "Messiness" mod]],
        quote = [[The only constant in life is change.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- GV
        id = 'GV',
        name = "The Tower",
        desc = [[HFD with the "Gravity" mod]],
        quote = [[What will you do when it all comes crumbling down?]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- VL
        id = 'VL',
        name = "Strength",
        desc = [[HFD with the "Volatility" mod]],
        quote = [[Match great obstacles with greater determination.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- DH
        id = 'DH',
        name = "The Devil",
        desc = [[HFD with the "Double Hole" mod]],
        quote = [[Redifine your limits or succumb to his chains.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- IN
        id = 'IN',
        name = "The Hermit",
        desc = [[HFD with the "Invisible" mod]],
        quote = [[When the outside world fails you, trust the voice within to light a path.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- AS
        id = 'AS',
        name = "The Magician",
        desc = [[HFD with the "All-Spin" mod]],
        quote = [[Inspiration is nothing short of magic.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- DP
        id = 'DP',
        name = "The Lovers",
        desc = [[HFD with the "Duo" mod]],
        quote = [[Love, and resign yourself to the fate of another.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
        hide = function() return not ACHV.intended_glitch end,
    },
    { -- GVIN
        id = 'GVIN',
        name = "The Grandmaster",
        desc = [[HFD WUT "Gravity" and "Invisible" mods]],
        quote = [[When the world descends into chaos, the grandmaster remains at peace.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- ASNH
        id = 'ASNH',
        name = "The Starving Artist",
        desc = [[HFD WUT "No Hold" and "All-Spin" mods]],
        quote = [[Creativity cultivated trough limitation.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- DPEX
        id = 'DPEX',
        name = "Trained Professionals",
        desc = [[HFD WUT "Expert Mode" and "Duo" mods]],
        quote = [[Partners in expertise.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- GVNH
        id = 'GVNH',
        name = "A Modern Classic",
        desc = [[HFD WUT "No Hold" and "Gravity" mods]],
        quote = [[Times were different back then...]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- DHMSNH
        id = 'DHMSNH',
        name = "Deadlock",
        desc = [[HFD WUT "No Hold", "Messiness" and "Double Hole" mods]],
        quote = [["Escape has become a distant dream, yet still we struggle..."]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- DHEXNH
        id = 'DHEXNH',
        name = "Emperor's Decadence",
        desc = [[HFD WUT "Expert Mode", "No Hold" and "Double Hole" mods]],
        quote = [[The Devil's lesson in humility.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- DHEXMSVL
        id = 'DHEXMSVL',
        name = "Divine Mastery",
        desc = [[HFD WUT "Expert Mode", "Messiness", "Volatility" and "Double Hole" mods]],
        quote = [[The universe is yours.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
    },
    { -- ASEXVL
        id = 'ASEXVL',
        name = "The Con Artist",
        desc = [[HFD WUT "Expert Mode", "Volatility" and "All-Spin" mods]],
        quote = [[Would the perfect lie not be an art worthy of admiration?]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- swamp_water_lite
        id = 'swamp_water_lite',
        name = "Swamp Water Lite",
        desc = [[HFD WU 7/8 of the difficulty mods ("Duo" doesn't count)]],
        quote = [[Comes in 8 different flavors!]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- swamp_water
        id = 'swamp_water',
        name = "Swamp Water",
        desc = [[HFD WU all mods ("Duo" doesn't count)]],
        quote = [[The worst of all worlds.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
    },

    { title = "Reversed Mods", hide = function() return TABLE.countAll(GAME.completion, 0) == 9 end },
    { -- rEX
        id = 'rEX',
        name = "The Tyrant",
        desc = [[HFD with the reversed "Expert Mode" mod]],
        quote = [[Fear, oppression, and limitless ambition.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 1800),
        hide = function() return GAME.completion.EX == 0 end,
    },
    { -- rNH
        id = 'rNH',
        name = "Asceticism",
        desc = [[HFD with the reversed "No Hold" mod]],
        quote = [[A detachment from even that which is moderate.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return GAME.completion.NH == 0 end,
    },
    { -- rMS
        id = 'rMS',
        name = "Loaded Dice",
        desc = [[HFD with the reversed "Messiness" mod]],
        quote = [[In a rigged game, your mind is the only fair advantage.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return GAME.completion.MS == 0 end,
    },
    { -- rGV
        id = 'rGV',
        name = "Freefall",
        desc = [[HFD with the reversed "Gravity" mod]],
        quote = [[In retrospect, the ground you stood on never existed in the first place.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return GAME.completion.GV == 0 end,
    },
    { -- rVL
        id = 'rVL',
        name = "Last Stand",
        desc = [[HFD with the reversed "Volatility" mod]],
        quote = [[Strength isn't necessary for those with nothing to lose.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return GAME.completion.VL == 0 end,
    },
    { -- rDH
        id = 'rDH',
        name = "Damnation",
        desc = [[HFD with the reversed "Double Hole" mod]],
        quote = [[Neither the freedom of life or peace of death.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return GAME.completion.DH == 0 end,
    },
    { -- rIN
        id = 'rIN',
        name = "The Exile",
        desc = [[HFD with the reversed "Invisible" mod]],
        quote = [[Never underestimate blind faith.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return GAME.completion.IN == 0 end,
    },
    { -- rAS
        id = 'rAS',
        name = "The Warlock",
        desc = [[HFD with the reversed "All-Spin" mod]],
        quote = [[Into realms beyond heaven and earth.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
        hide = function() return GAME.completion.AS == 0 end,
    },
    { -- rDP
        id = 'rDP',
        name = "Bleeding Hearts",
        desc = [[HFD with the reversed "Duo" mod]],
        quote = [[Even as we bleed, we keep holding on...]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return GAME.completion.DP == 0 end,
    },
    { -- rGVrIN
        ex = true,
        id = 'rGVrIN',
        name = "The Grandmaster+",
        desc = [[HFD with rGV rIN mods]],
        quote = [[Even when the universe collapses, the real grandmaster still remains at peace.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return GAME.completion.GV == 0 or GAME.completion.IN == 0 end,
    },
    { -- EXNHrAS
        ex = true,
        id = 'EXNHrAS',
        name = "Magic School",
        desc = [[HFD with EX NH rAS mods]],
        quote = [[Diplomas are only awarded to those who have truly mastered their craft.]],
        credit = "@GameTilDead",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return GAME.completion.AS == 0 end,
    },
    { -- INrASrDHrNH
        ex = true,
        id = 'INrASrDHrNH',
        name = "The Spellcaster",
        desc = [[HFD with rNH rDH IN rAS mods]],
        quote = [[Mastery of spells with precision in all scenarios made from your memory.]],
        credit = "@The_111thBlitzer",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return GAME.completion.NH == 0 or GAME.completion.DH == 0 or GAME.completion.AS == 0 end,
    },
    { -- DHEXrGV
        ex = true,
        id = 'DHEXrGV',
        name = "Demonic Speed",
        desc = [[HFD with EX rGV DH mods]],
        quote = [[Prove your hellish capabilities to the world.]],
        credit = "@GameTilDead",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return GAME.completion.GV == 0 end,
    },
    { -- EXGVNHrMS
        ex = true,
        id = 'EXGVNHrMS',
        name = "Bnuuy",
        desc = [[HFD with EX NH rMS GV mods]],
        quote = [[Look at them hopping around! Too bad they don't want to be picked up...]],
        credit = "@GameTilDead",
        rank = floorRank(1, 3, 5, 7, 9, 10, 1800),
        hide = function() return GAME.completion.MS == 0 end,
    },
    { -- ASDPGVrMSrNH
        ex = true,
        id = 'ASDPGVrMSrNH',
        name = "Grand-Master! Rounds",
        desc = [[HFD with rNH rMS GV AS DP mods]],
        quote = [[YOUR AER: GRAND-MASTER! Rounds]],
        rank = floorRank(1, 3, 5, 7, 8, 9, 10),
        hide = function() return GAME.completion.NH == 0 or GAME.completion.MS == 0 end,
    },
    { -- DHrEXrVL
        ex = true,
        id = 'DHrEXrVL',
        name = "Sweat and Ruin",
        desc = [[HFD with rEX rVL DH mods]],
        quote = [[Put your blood, sweat, and tears into the climb, or fall.]],
        credit = "@Tizago",
        rank = floorRank(1, 3, 5, 6, 7, 8, 9),
        hide = function() return GAME.completion.EX == 0 end,
    },
    { -- ASGVrDPrMS
        ex = true,
        id = 'ASGVrDPrMS',
        name = "Cupid's Gamble",
        desc = [[HFD with rMS GV AS rDP]],
        quote = [[In the age of lust and infidelity, true love is only a gamble...]],
        credit = "@FMichael",
        rank = floorRank(1, 3, 5, 6, 7, 8, 9),
        hide = function() return GAME.completion.MS == 0 or GAME.completion.DP == 0 end,
    },
    { -- NHVLrDPrGV
        ex = true,
        id = 'NHVLrDPrGV',
        name = "Despairful Longing",
        desc = [[HFD with NH rGV VL rDP mods]],
        quote = [[A worthless, desperate attempt at saving a shattered, withered love...]],
        credit = "@FMichael",
        rank = floorRank(1, 3, 5, 6, 7, 8, 9),
        hide = function() return GAME.completion.GV == 0 or GAME.completion.DP == 0 end,
    },
    { -- VLrEXrIN
        ex = true,
        id = 'VLrEXrIN',
        name = "Authoritarian Delusion",
        desc = [[HFD with rEX VL rIN]],
        quote = [[Corrupted sovereignty, exploited law and a blind thirst for more...]],
        credit = "@FMichael",
        rank = floorRank(1, 3, 4, 5, 6, 7, 8),
        hide = function() return GAME.completion.EX == 0 or GAME.completion.IN == 0 end,
    },
    { -- rDPrEX
        ex = true,
        id = 'rDPrEX',
        name = "Tyrannical Dyarchy",
        desc = [[HFD with rEX rDP mods]],
        quote = [[Live in fear and despair.]],
        rank = floorRank(1, 3, 4, 5, 6, 7, 8),
        hide = function() return GAME.completion.EX == 0 or GAME.completion.DP == 0 end,
    },
    { -- INMSrDHrEX
        ex = true,
        id = 'INMSrDHrEX',
        name = "Sisyphean Monarchy",
        desc = [[HFD with rEX MS rDH IN mods]],
        quote = [[Ruling an unruly empire on the brink of collapse.]],
        credit = "@Tizago",
        rank = floorRank(1, 2, 3, 4, 5, 6, 7),
        hide = function() return GAME.completion.EX == 0 or GAME.completion.DH == 0 end,
    },
    { -- ASMSrDHrIN
        ex = true,
        id = 'ASMSrDHrIN',
        name = "Kitsune Trickery",
        desc = [[HFD with MS rDH rIN AS mods]],
        quote = [[Charming at first glance, with many dark secrets beneath their magic and fur.]],
        credit = "@Tizago",
        rank = floorRank(1, 26, 42, 2, 3, 4, 6),
        hide = function() return GAME.completion.DH == 0 or GAME.completion.IN == 0 end,
    },
    { -- swamp_water_lite_plus
        ex = true,
        id = 'swamp_water_lite_plus',
        name = "Ambrosia Soda",
        desc = [[HFD WU 1 reverse mod + 6 mods ("Duo" doesn't count)]],
        quote = [[A watered down solution, which comes in 56 peculiar flavors.]],
        credit = "@FMichael",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return TABLE.countAll(GAME.completion, 0) == 9 end,
    },
    { -- swamp_water_plus
        ex = true,
        id = 'swamp_water_plus',
        name = "Ambrosia Wine",
        desc = [[HFD WU 1 reverse mod + 7 mods ("Duo" doesn't count)]],
        quote = [[Potent, intoxicating wine, coming in 8 electrifying flavors.]],
        credit = "@FMichael",
        rank = floorRank(1, 3, 5, 7, 9, 10, 1800),
        hide = function() return TABLE.countAll(GAME.completion, 0) == 9 end,
    },

    { title = "Special" },
    { -- talentless
        id = 'talentless',
        name = "Talentless",
        desc = [[HFD without using keyboard WUT "All-Spin" mod]],
        quote = [[Reaching deep down but coming back empty every time.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- quest_rationing
        id = 'quest_rationing',
        name = "Quest Rationing",
        desc = [[Highest altitude on 40 quests WUT "Expert Mode" and "Messiness" mods]],
        quote = [[Adversity favors the resourceful.]],
        scoreSimp = heightNumber,
        rank = numberRank(0, 260, 360, 450, 495, 550, 600),
    },
    { -- the_responsible_one
        id = 'the_responsible_one',
        name = "The Responsible One",
        desc = [[Highest amount of revivals performed in a single Duo run]],
        quote = [["Could you please stop dying?"]],
        scoreSimp = function(revive) return revive .. " Revives" end,
        rank = numberRank(0, 3, 5, 8, 10, 12, 15),
    },
    { -- the_unreliable_one
        ex = true,
        id = 'the_unreliable_one',
        name = "The Unreliable One",
        desc = [[Highest amount of KILLs in a single reversed Duo run]],
        quote = [["I'll never let you off."]],
        scoreSimp = function(kill) return kill .. " Kills" end,
        rank = numberRank(0, 2, 3, 4, 5, 6, 8),
        hide = function() return GAME.completion.DP == 0 end,
    },
    { -- the_responsible_one_plus
        ex = true,
        id = 'the_responsible_one_plus',
        name = "The Responsible One+",
        desc = [[Highest amount of revivals performed, multiplied by MP]],
        quote = [["Is this going to be a recurring theme?"]],
        credit = "@FCSplayz",
        scoreSimp = function(rank) return floor(rank) .. " Points" end,
        rank = numberRank(0, 16, 26, 36, 49, 64, 81),
    },
    { -- guardian_angel
        id = 'guardian_angel',
        name = "Guardian Angel",
        desc = [[Highest altitude to perform a successful revive at]],
        quote = [[An angel's intervention.]],
        scoreSimp = heightNumber,
        rank = numberRank(0, 626, 942, 1620, 2000, 2600, 4200),
    },
    { -- carried
        ex = true,
        id = 'carried',
        name = "Carried",
        desc = [[HFD without passing any quest with both players alive, with at least DP]],
        quote = [["I have no idea how to play the game, can you unlock the mods for me?"]],
        credit = "@obsidian",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
    },
    { -- level_19_cap
        ex = true,
        id = 'level_19_cap',
        name = "Level 19 Cap",
        desc = [[HAR before first fatigue effect, with NH]],
        quote = [[Another test of sustained speed and efficiency.]],
        credit = "@Ponies",
        rank = floorRank(1, 9, 10, 2000, 2400, 2600, 3500),
    },
    { -- the_escape_artist
        id = 'the_escape_artist',
        name = "The Escape Artist",
        desc = [[Quests passed with wounds triggered WUT "Double Hole", "Messiness" and "All-Spin" mods]],
        quote = [["An impossible situation! A daring illusionist! Will he make it out alive?"]],
        scoreSimp = function(quest) return floor(quest) .. " Quests" end,
        rank = numberRank(0, 10, 26, 40, 60, 80, 100),
    },
    { -- fel_magic
        ex = true,
        id = 'fel_magic',
        name = "Fel Magic",
        desc = [[Quests passed with wounds triggered during GIGASPEED, with rAS]],
        quote = [["And what, Gul'dan, must we give it return?"]],
        scoreSimp = function(quest) return floor(quest) .. " Quests" end,
        rank = numberRank(0, 6, 15, 26, 42, 62, 80),
        hide = function() return GAME.completion.AS == 0 or STAT.totalGiga == 0 end,
    },
    { -- empurple
        ex = true,
        id = 'empurple',
        name = "Empurple",
        desc = [[HFD without building up a surge, with VL DH rIN]],
        quote = [[Iteration after iteration after iteration, searching for the perfect shade...]],
        credit = "@obsidian",
        rank = floorRank(1, 3, 5, 7, 9, 10, 1800),
        hide = function() return GAME.completion.IN == 0 end,
    },
    { -- faltered
        ex = true,
        id = 'faltered',
        name = "Faltered",
        desc = [[HFD without building up a surge, with EX NH MS VL rAS]],
        quote = [[Attaining power is only temporary, it fades faster than what you can attain.]],
        credit = "@The_111thBlitzer",
        rank = floorRank(1, 3, 4, 5, 7, 8, 10),
        hide = function() return GAME.completion.AS == 0 end,
    },
    { -- patience_is_a_virtue
        ex = true,
        id = 'patience_is_a_virtue',
        name = "Patience is a Virtue",
        desc = [[HFD without manually committing]],
        quote = [[Opportunities always favor those who are prepared and wait.]],
        credit = "@The_111thBlitzer",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
    },
    { -- one_of_mine
        ex = true,
        id = 'one_of_mine',
        name = "But It Isn't One Of Mine",
        desc = [[Reach F10 while maintaining TERASPEED and not manually committing with at least eEX, uGV, and eDH +eZ]],
        quote = [["Ain't nobody got time for that!"]],
        credit = "@TrevorSmithy",
        type = 'issued',
    },
    { -- spotless
        ex = true,
        id = 'spotless',
        name = "Spotless",
        desc = [[HFD without taking any damage, with rGV]],
        quote = [["Not even a single scratch on me!"]],
        credit = "@FCSplayz",
        rank = floorRank(1, 3, 5, 7, 8, 9, 10),
        hide = function() return GAME.completion.GV == 0 end,
    },
    { -- a_mutual_agreement
        ex = true,
        id = 'a_mutual_agreement',
        name = "A Mutual Agreement",
        desc = [[HFD with DH AS DP with every commit sharing at least 1 mod with the previous one]],
        quote = [[Signed in writing, binding hearts and hands alike.]],
        credit = "@FCSplayz",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2200),
    },
    { -- the_cheaters
        ex = true,
        id = 'the_cheaters',
        name = "The Cheaters",
        desc = [[HFD with VL AS DP with commit not sharing any mod with the previous one]],
        quote = [[Hearts broken from whom you stay with, to bond with another.]],
        credit = "@Patrickmlg",
        rank = floorRank(1, 3, 5, 6, 7, 8, 10),
    },
    { -- overprotection
        ex = true,
        id = 'overprotection',
        name = "Overprotection",
        desc = [[HFD while keeping both players' HP above 10/15, with rDP]],
        quote = [["Are you hurt? Did I hurt you?"]],
        credit = "@obsidian",
        rank = floorRank(1, 3, 5, 6, 7, 8, 9),
        hide = function() return GAME.completion.DP == 0 end,
    },
    { -- clutch_main
        ex = true,
        id = 'clutch_main',
        name = "Clutch Main",
        desc = [[Quests passed while HP is critical, with NH rGV]],
        quote = [[Your horses had better be held onto!]],
        credit = "@GameTilDead",
        scoreSimp = function(quest) return floor(quest) .. " Quests" end,
        rank = numberRank(0, 26, 42, 62, 94, 126, 162),
        hide = function() return GAME.completion.GV == 0 end,
    },
    { -- sunk_cost
        ex = true,
        id = 'sunk_cost',
        name = "Sunk Cost",
        desc = [[HFD without losing a rank]],
        quote = [[Cross the line, and the descent begins.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
    },
    { -- wax_wings
        ex = true,
        id = 'wax_wings',
        name = "Wax Wings",
        desc = [[HFD without losing a rank, with EX VL]],
        quote = [["Bold in vanity, began to soar, rising upon his wings to touch the skies."]],
        credit = "@Flowerling",
        rank = floorRank(1, 3, 5, 7, 8, 9, 10),
    },
    { -- the_masterful_juggler
        ex = true,
        id = 'the_masterful_juggler',
        name = "The Masterful Juggler",
        desc = [[Highest Back-to-Back chain reached, with rMS rGV rIN]],
        quote = [[A perfect jester, putting memory, speed and technique into entertainment...]],
        credit = "@FMichael",
        scoreSimp = function(b2b) return "B2B x" .. b2b end,
        rank = numberRank(0, 10, 18, 26, 42, 62, 94),
        hide = function() return GAME.completion.MS == 0 or GAME.completion.GV == 0 or GAME.completion.IN == 0 end,
    },
    { -- the_oblivious_artist
        ex = true,
        id = 'the_oblivious_artist',
        name = "The Oblivious Artist",
        desc = [[Quests passed by using SPIN an odd amount of times, with DH rIN AS]],
        quote = [[They're a little confused but got the spirit!]],
        credit = "@Tizago",
        scoreSimp = function(quest) return floor(quest) .. " Quests" end,
        rank = numberRank(0, 12, 26, 40, 50, 60, 80),
        hide = function() return GAME.completion.IN == 0 end,
    },
    { -- zero_to_sixty
        ex = true,
        id = 'zero_to_sixty',
        name = "Zero-to-sixty",
        desc = [[Fastest time to reach Gigaspeed using NH rVL AS]],
        quote = [["Didn't even need the 1-foot rollout!"]],
        comp = '<',
        credit = "@FCSplayz",
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(42, 26, 16, 13, 11, 10, 8),
        hide = function() return GAME.completion.VL == 0 or STAT.totalGiga == 0 end,
    },
    { -- speed_bonus
        ex = true,
        id = 'speed_bonus',
        name = "Speed Bonus",
        desc = [[Trigger any speedrun animation as many times as possible within a single run, without using rEX or rDP]],
        quote = [[Three steps forward, two steps back. Six steps forward, five steps back.]],
        scoreSimp = function(kill) return kill .. " Entries" end,
        rank = numberRank(0, 2, 3, 3, 4, 4, 5),
    },
    { -- arrogance
        ex = true,
        id = 'arrogance',
        name = "Arrogance",
        desc = [[HAR without getting perfect passes, with rAS]],
        quote = [[Maintaining arrogance constantly is not easy.]],
        rank = numberRank(10, 16, 26, 42, 50, 100, 150),
        hide = function() return GAME.completion.AS == 0 end,
    },
    { -- scarcity_mindset
        id = 'scarcity_mindset',
        name = "Scarcity Mindset",
        desc = [[Least flips spent completing 40 quests with rNH MS DP]],
        quote = [[Excessive restraint can make one deeply entangled in it.]],
        comp = '<',
        scoreSimp = function(flip) return floor(flip) .. " Flips" end,
        rank = numberRankRev(90, 86, 84, 82, 80, 77, 74),
        hide = function() return GAME.completion.NH == 0 end,
    },
    { -- detail_oriented
        id = 'detail_oriented',
        name = "Detail Oriented",
        desc = [[Fewest flips used to reach F10]],
        quote = [[Theoretically efficient can quickly become gloriously impractical.]],
        comp = '<',
        scoreSimp = function(flip) return floor(flip) .. " Flips" end,
        rank = numberRankRev(260, 240, 220, 200, 180, 150, 100),
    },
    { -- psychokinesis
        ex = true,
        id = 'psychokinesis',
        name = "Psychokinesis",
        desc = [[HAR without manually flipping]],
        quote = [[Real magic exists!]],
        rank = floorRank(26, 42, 62, 126, 3, 4, 5),
    },
    { -- divine_rejection
        ex = true,
        id = 'divine_rejection',
        name = "Divine Rejection",
        desc = [[End a run just before F10]],
        quote = [[A blinding flash of light, a painful crash to the bottom.]],
        credit = '@Flowerling',
        scoreSimp = function(h) return string.format("%.1fm", h) end,
        rank = numberRank(1626, 1626, 1635, 1640, 1645, 1647.8, 1649),
    },
    { -- fickle_fuel
        ex = true,
        id = 'fickle_fuel',
        name = "Fickle Fuel",
        desc = [[Altitude gained through surge using rGV VL]],
        quote = [[T-minus 5, 4, 3, 2, 1, Lift off!]],
        credit = "@The_111thBlitzer",
        scoreSimp = function(h) return string.format("%.1fm", h) end,
        rank = numberRank(0, 260, 300, 350, 420, 500, 620),
        hide = function() return GAME.completion.GV == 0 end,
    },
    { -- moon_struck
        ex = true,
        id = 'moon_struck',
        name = "Moon Struck",
        desc = [[Finish the run at exactly 2202.8m]],
        quote = [["With this moonlight as my witness, will you take my hand for eternity?"]],
        comp = '<',
        scoreSimp = function(dist) return dist == 0 and "Flawless Landing!" or string.format("%.1fm away", dist) end,
        rank = numberRankRev(26, 16, 8, 4, 2, 1, 0),
        credit = "@osk",
    },
    { -- lovers_promise
        id = 'lovers_promise',
        name = "Lover's Promise",
        desc = [[HAR with DP on the 14th day of any month]],
        quote = [[The impossible promise of an eternity just like this moment.]],
        scoreSimp = heightNumber,
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        type = 'event',
    },

    { title = "Supercharged Clone", credit = "@Garbo" },
    { -- hardcore_beginning
        ex = true,
        id = 'hardcore_beginning',
        name = "Hardcore Beginning",
        desc = [[Shortest time spent in F1 with rEX rNH rVL]],
        quote = [[A race to the sky, but everyone in the world will make sure that will be a fantasy.]],
        credit = "@F1e308",
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", (Floors[1].top - Floors[0].top) / time) end,
        rank = numberRankRev(62, 50, 42, 36, 30, 26, 22),
        hide = function() return GAME.completion.EX == 0 or GAME.completion.NH == 0 or GAME.completion.VL == 0 end,
    },
    { -- love_hotel
        ex = true,
        id = 'love_hotel',
        name = "Love Hotel",
        desc = [[Shortest time spent in F2 with EX VL rIN rDP]],
        quote = [[A nice place for a quick visit.]],
        credit = "@obsidian",
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", (Floors[2].top - Floors[1].top) / time) end,
        rank = numberRankRev(26, 22, 18, 15, 12, 9.4, 6.2),
        hide = function() return GAME.completion.IN == 0 or GAME.completion.DP == 0 end,
    },
    { -- financially_responsible
        ex = true,
        id = 'financially_responsible',
        name = "Financially Responsible",
        desc = [[Shortest time spent in F3 with EX MS AS]],
        quote = [[No time for distractions, focus on your main goal.]],
        credit = "@GameTilDead",
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", (Floors[3].top - Floors[2].top) / time) end,
        rank = numberRankRev(32, 26, 22, 19.4, 16.2, 12.6, 9.42),
    },
    { -- unfair_battle
        ex = true,
        id = 'unfair_battle',
        name = "Unfair Battle",
        desc = [[Shortest time spent in F4 with EX rVL rDP]],
        quote = [[Quick moves and careful maneuvers, this round can be over in the blink of an eye!]],
        credit = "@Tizago",
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", (Floors[4].top - Floors[3].top) / time) end,
        rank = numberRankRev(32, 26, 22, 19.4, 16.2, 12.6, 9.42),
        hide = function() return GAME.completion.VL == 0 or GAME.completion.DP == 0 end,
    },
    { -- museum_heist
        ex = true,
        id = 'museum_heist',
        name = "Museum Heist",
        desc = [[Shortest time spent in F5 with DH DP]],
        quote = [[Less time, less evidence.]],
        credit = "@Baron",
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", (Floors[5].top - Floors[4].top) / time) end,
        rank = numberRankRev(42, 26, 16, 12, 9.42, 6.2, 3.5),
    },
    { -- workaholic
        ex = true,
        id = 'workaholic',
        name = "Workaholic",
        desc = [[Shortest time spent in F6 with EX rGV VL]],
        quote = [[An unhealthy obsession over never-ending papers and unrealistic deadlines...]],
        credit = "@FMichael",
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", (Floors[6].top - Floors[5].top) / time) end,
        rank = numberRankRev(42, 26, 16, 12, 9.42, 6.2, 4.2),
        hide = function() return GAME.completion.GV == 0 end,
    },
    { -- human_experiment
        ex = true,
        id = 'human_experiment',
        name = "Human Experiment",
        desc = [[Shortest time spent in F7 with MS VL AS]],
        quote = [["You can assure me that this is safe, right?"]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", (Floors[7].top - Floors[6].top) / time) end,
        rank = numberRankRev(42, 26, 16, 12, 9.42, 6.2, 4.2),
    },
    { -- thermal_anomaly
        ex = true,
        id = 'thermal_anomaly',
        name = "Thermal Anomaly",
        desc = [[Shortest time spent in F8 with EX GV DH]],
        quote = [["This can't be real." As the overloaded core melts down before my eyes.]],
        credit = "@obsidian",
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", (Floors[8].top - Floors[7].top) / time) end,
        rank = numberRankRev(62, 30, 26, 16, 6.2, 2.6, 1.0),
    },
    { -- ultra_dash
        ex = true,
        id = 'ultra_dash',
        name = "Ultra Dash",
        desc = [[Shortest time spent in F9]],
        quote = [[Probably a good strategy for speedrunning 1.2x faster.]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.1f m/s", (Floors[9].top - Floors[8].top) / time) end,
        rank = numberRankRev(62, 26, 16, 12, 6.2, 2.6, 1.0),
    },
    { -- perfect_speedrun
        ex = true,
        id = 'perfect_speedrun',
        name = "Perfect Speedrun",
        desc = [[Fastest time to reach 75 B2B]],
        quote = [[Supercharged B75%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        scoreFull = function(time) return string.format("%.2f quests/s", 75 / time) end,
        rank = numberRankRev(150, 115, 90, 70, 60, 50, 42),
    },
    { -- the_perfectionist
        ex = true,
        id = 'the_perfectionist',
        name = "The Perfectionist",
        desc = [[HFD without imperfect pass or damage taken]],
        quote = [[Supercharged Perf%]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- cruise_control
        ex = true,
        id = 'cruise_control',
        name = "Cruise Control",
        desc = [[Highest rank maintained for at least 1 min in one run]],
        quote = [[Ascending the tower at a stable, yet swift rate.]],
        credit = "@FMichael",
        scoreSimp = function(rank) return "Rank " .. (rank == 26 and "26 (Max)" or rank) end,
        rank = numberRank(10, 12, 13, 14, 15, 16, 18),
    },
    { -- dazed
        ex = true,
        id = 'dazed',
        name = "Dazed",
        desc = [[Highest rank when hitting F10 with MS GV AS]],
        quote = [[Illusions dance around you...]],
        credit = "@The_111thBlitzer",
        scoreSimp = function(rank) return "Rank " .. rank end,
        rank = numberRank(10, 10, 11, 12, 13, 14, 16),
    },
    { -- drag_racing
        ex = true,
        id = 'drag_racing',
        name = "Drag Racing",
        desc = [[Highest (climb speed) rank reached]],
        quote = [[Blaze past the competition with unreal speeds to achieve momentary greatness.]],
        credit = "@GameTilDead",
        scoreSimp = function(rank) return "Rank " .. rank end,
        rank = numberRank(12, 14, 15, 16, 17, 18, 20),
    },
    { -- space_race
        ex = true,
        id = 'space_race',
        name = "Space Race",
        desc = [[Highest rank*MP]],
        quote = [[So you found the rockets, huh? Why not take them where they belong?]],
        credit = "@GameTilDead",
        scoreSimp = function(rank) return rank .. " Rank·MP" end,
        rank = numberRank(42, 62, 74, 87.2, 100, 126, 162),
    },
    { -- the_spike_of_all_time_plus
        ex = true,
        id = 'the_spike_of_all_time_plus',
        name = "The Spike of All Time+",
        desc = [[Largest spike sent]],
        quote = [[...and others prefer rewriting their destiny with divine power.]],
        credit = "@GameTilDead",
        scoreSimp = function(spike) return floor(spike) .. " Spike" end,
        rank = numberRank(0, 10, 26, 42, 62, 126, 200),
    },

    { title = "Why",                hide = function() return TABLE.countAll(GAME.completion, 0) >= 8 end, credit = "@MrZ @Flowerling" },
    { -- blight
        ex = true,
        id = 'blight',
        name = "Blight",
        desc = [[HFD with 8+ mod points (at least 2 reversed mods)]],
        quote = [[Power starts to leak out...]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 7 end,
    },
    { -- desolation
        ex = true,
        id = 'desolation',
        name = "Desolation",
        desc = [[HFD with 9+ mod points (at least 2 reversed mods)]],
        quote = [[...it begins corrupting the world...]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 7 end,
    },
    { -- havoc
        ex = true,
        id = 'havoc',
        name = "Havoc",
        desc = [[HFD with 10+ mod points (at least 2 reversed mods)]],
        quote = [[...things start going wrong...]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 1800),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 7 end,
    },
    { -- pandemonium
        ex = true,
        id = 'pandemonium',
        name = "Pandemonium",
        desc = [[HFD with 11+ mod points]],
        quote = [[...the cacophony grows louder...]],
        rank = floorRank(1, 2, 4, 6, 8, 9, 10),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 7 end,
    },
    { -- inferno
        ex = true,
        id = 'inferno',
        name = "Inferno",
        desc = [[HFD with 12+ mod points]],
        quote = [[...the agony spreads like wildfire...]],
        rank = floorRank(1, 2, 4, 6, 7, 8, 9),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 6 end,
    },
    { -- purgatory
        ex = true,
        id = 'purgatory',
        name = "Purgatory",
        desc = [[HAR with 13+ mod points]],
        quote = [[...is escape ever possible?...]],
        rank = numberRank(0, 50, 300, 400, 500, 600, 800),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 5 end,
    },
    { -- perdition
        ex = true,
        id = 'perdition',
        name = "Perdition",
        desc = [[HAR with 14+ mod points]],
        quote = [[...is this some sort of punishment?...]],
        rank = numberRank(0, 50, 250, 300, 350, 400, 600),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 4 end,
    },
    { -- cataclysm
        ex = true,
        id = 'cataclysm',
        name = "Cataclysm",
        desc = [[HAR with 15+ mod points]],
        quote = [[...this disaster could have been stopped...]],
        rank = numberRank(0, 50, 200, 250, 300, 350, 500),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 3 end,
    },
    { -- annihilation
        ex = true,
        id = 'annihilation',
        name = "Annihilation",
        desc = [[HAR with 16+ mod points]],
        quote = [[...but now everything is being destroyed...]],
        rank = numberRank(0, 50, 150, 200, 250, 300, 400),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 2 end,
    },
    { -- armageddon
        ex = true,
        id = 'armageddon',
        name = "Armageddon",
        desc = [[HAR with 17+ mod points]],
        quote = [[...we have all been doomed...]],
        rank = numberRank(0, 20, 50, 75, 100, 150, 200),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 1 end,
    },
    { -- abyss
        ex = true,
        id = 'abyss',
        name = "Abyss",
        desc = [[HAR with 18 mod points]],
        quote = [[...and there is nothing left for us anymore.]],
        rank = numberRank(0, 20, 30, 40, 50, 75, 100),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 0 end,
    },

    { title = "Issued-Gameplay (No CR)" },
    { -- cut_off
        ex = true,
        id = 'cut_off',
        name = "Cut Off",
        desc = [[Lose GIGASPEED above 1600m on F9]],
        quote = [[Tripped right at the finish line!]],
        type = 'issued',
        hide = function() return STAT.totalGiga == 0 end,
    },
    { -- worn_out
        ex = true,
        id = 'worn_out',
        name = "Worn Out",
        desc = [[Reach F10 with GIGASPEED after retaining it for 5 minutes]],
        quote = [[You alright over there? You seem a bit tired from all that "speed"-running...]],
        credit = "@GameTilDead",
        type = 'issued',
        hide = function() return STAT.totalGiga == 0 end,
    },
    { -- the_harbinger
        id = 'the_harbinger',
        name = "The Harbinger",
        desc = [[Reach floor 5 in all nine reversed mods]],
        quote = [[Weathering the storm of an unfavorable future.]],
        hide = TRUE,
        type = 'issued',
    },
    { -- final_defiance
        ex = true,
        id = 'final_defiance',
        name = "Final Defiance",
        desc = [[Meet the final fatigue effect]],
        quote = [["This is not the end!"]],
        credit = "@Flowerling",
        type = 'issued',
    },
    { -- speedrun_speedrunning
        ex = true,
        id = 'speedrun_speedrunning',
        name = "Speedrun Speedrunning",
        desc = [[Enter GIGASPEED on F1]],
        quote = [[Not much of a speedrun]],
        type = 'issued',
        hide = function() return STAT.totalGiga == 0 end,
    },
    { -- abyss_weaver
        ex = true,
        id = 'abyss_weaver',
        name = "Abyss Weaver",
        desc = [[Enter GIGASPEED with 15+ mod points]],
        quote = [[Skills and mastery of the void beyond any mortals' comprehension.]],
        credit = "@Tizago",
        type = 'issued',
        hide = function() return TABLE.countAll(GAME.completion, 0) > 3 end,
    },
    { -- royal_resistance
        ex = true,
        id = 'royal_resistance',
        name = "Royal Resistance",
        desc = [[Meet the final fatigue effect with rEX]],
        quote = [["History will prove me right!!"]],
        credit = "@Flowerling",
        hide = function() return GAME.completion.EX == 0 end,
        type = 'issued',
    },
    { -- lovers_stand
        ex = true,
        id = 'lovers_stand',
        name = "Lover's Stand",
        desc = [[Meet the final fatigue effect with rDP]],
        quote = [[The power of affection sees you through the bitter end.]],
        hide = function() return GAME.completion.DP == 0 end,
        type = 'issued',
    },
    { -- romantic_homicide
        ex = true,
        id = 'romantic_homicide',
        name = "Romantic Homicide",
        desc = [[Survive after breaking B2B x 62 while using rDP and one player is KO'd]],
        quote = [["As I bleed out, I realize now the consequences of my foolishness..."]],
        credit = "@FMichael",
        hide = function() return GAME.completion.DP == 0 end,
        type = 'issued',
    },
    { -- benevolent_ambition
        ex = true,
        id = 'benevolent_ambition',
        name = "Benevolent Ambition",
        desc = [[Revive after "NO REVIVE" fatigue, with rDP]],
        quote = [["I'll come... to save you..."]],
        credit = "@obsidian",
        hide = function() return GAME.completion.DP == 0 end,
        type = 'issued',
    },
    { -- blazing_speed
        ex = true,
        id = 'blazing_speed',
        name = "Blazing Speed",
        desc = [[Reach F10 while maintaining TERASPEED]],
        quote = [[Listen to the flames crackling louder.]],
        credit = "@The_111thBlitzer",
        hide = TRUE,
        type = 'issued',
    },
    { -- dusty_memories
        ex = true,
        id = 'dusty_memories',
        name = "Dusty Memories",
        desc = [[Master combo "Ambrosia Moonshine"]],
        quote = [[A secret menu brew, hidden from the public's view.]],
        credit = "@F1e308",
        type = 'issued',
    },
    { -- its_kinda_rare
        ex = true,
        id = 'its_kinda_rare',
        name = "It's Kinda Rare!",
        desc = [[Master a daily combo containing 2 reversed mods]],
        quote = [[Those who are both capable and fortunate deserve a lifetime reward.]],
        credit = "@GameTilDead",
        hide = TRUE,
        type = 'issued',
    },
    { -- fruitless_effort
        ex = true,
        id = 'fruitless_effort',
        name = "Fruitless Effort",
        desc = [[Finish a game with a bonus of over 260%]],
        quote = [[Effort is pointless if you are not strong enough.]],
        hide = function() return GAME.completion.EX == 0 end,
        type = 'issued',
    },
    { -- false_god
        ex = true,
        id = 'false_god',
        name = "False God",
        desc = [[Mastery on all mods]],
        quote = [[Deification paved by cheap tactics is not worth being proud of.]],
        type = 'issued',
        hide = TRUE,
    },
    { -- Programmer & Pro Gamer
        ex = true,
        id = 'programmer_gamer',
        name = "Programmer & Pro Gamer",
        desc = [[Reach F10 while maintaining TERASPEED WU eEX, eVL, and eAS]],
        quote = [["WAH-BAAM!"]],
        credit = "@TrevorSmithy",
        type = 'issued',
    },

    { title = "Issued-Misc (No CR)" },
    { -- identity
        ex = true,
        id = 'identity',
        name = "Identity",
        desc = [[Change your ID or "about me" section]],
        quote = [[Is this free?]],
        type = 'issued',
    },
    { -- respectful
        ex = true,
        id = 'respectful',
        name = "Respectful",
        desc = [[Stay in the ABOUT page for 26 seconds]],
        quote = [[Press F2 to pay respect]],
        type = 'issued',
    },
    { -- zenith_relocation
        ex = true,
        id = 'zenith_relocation',
        name = "Zenith Relocation",
        desc = [[Export your save to a different platform (including Web)]],
        quote = [[Uncover the mysteries of a new, familiar Tower.]],
        credit = "@GameTilDead",
        type = 'issued',
    },
    { -- intended_glitch
        ex = true,
        id = 'intended_glitch',
        name = "Intended Glitch",
        desc = [[Play Duo]],
        quote = [[The heart's lock yields to the artful understanding of spin.]],
        type = 'issued',
    },
    { -- lucky_coincidence
        ex = true,
        id = 'lucky_coincidence',
        name = "Lucky Coincidence",
        desc = [[Clear the first and second quest at the same time while using DP]],
        quote = [[An unexpected, spontaneous event leading into a new love.]],
        credit = "@FMichael",
        hide = function() return not ACHV.intended_glitch end,
        type = 'issued',
    },
    { -- zenith_traveler
        ex = true,
        id = 'zenith_traveler',
        name = "Zenith Traveler",
        desc = [[Enter traveler mode]],
        quote = [[Also known as background debugging mode]],
        type = 'issued',
    },
    { -- dark_force
        ex = true,
        id = 'dark_force',
        name = "Dark Force",
        desc = [[Interrupt font loading with rev mod]],
        quote = [[The darkness overflows.]],
        hide = TRUE,
        type = 'issued',
    },
    { -- return_to_the_light
        ex = true,
        id = 'return_to_the_light',
        name = "Return to the Light",
        desc = [[Reboot immediately when font not loaded]],
        quote = [[Not again...]],
        credit = "@FMichael",
        hide = TRUE,
        type = 'issued',
    },
    { -- smooth_dismount
        ex = true,
        id = 'smooth_dismount',
        name = "Smooth Dismount",
        desc = [[Reversing card animation ending in upright active state]],
        quote = [["And it sticks the landing!"]],
        credit = "@Flowerling",
        hide = TRUE,
        type = 'issued',
    },
}

local compFunc = {
    ['>'] = function(a, b) return a - b > 1e-10 end,
    ['<'] = function(a, b) return b - a > 1e-10 end,
}

do
    local i = 1
    repeat
        local achv = Achievements[i]
        if achv.title then
            if i % 2 == 0 then
                table.insert(Achievements, i, {})
                i = i + 1
            end
            table.insert(Achievements, i + 1, {})
        end
        i = i + 1
    until i > #Achievements
end
for i = 1, #Achievements do
    local achv = Achievements[i]
    local id = achv.id
    if id then
        Achievements[id] = achv

        assert(type(id) == 'string', "Missing field 'name' - " .. id)
        assert(type(achv.name) == 'string', "Missing field 'name' - " .. id)

        assert(achv.desc, "Missing field 'desc' - " .. id)
        achv.desc = achv.desc
            :gsub("WUT", "while using the")
            :gsub("WU", "while using")
            :gsub("HFD", "Highest floor discovered")
            :gsub("HAR", "Highest altitude reached")

        assert(achv.quote, "Missing field 'quote' - " .. id)

        achv.credit = achv.credit or ""

        if achv.comp == nil then
            achv.comp = compFunc['>']
        elseif compFunc[achv.comp] then
            if achv.comp == '<' then achv.noScore = 26000 end
            achv.comp = compFunc[achv.comp]
        elseif type(achv.comp) ~= 'function' then
            error("Invalid field 'comp' - " .. id)
        end

        if achv.type == nil then achv.type = 'competitive' end
        assert(type(achv.type) == 'string', "Invalid field 'type' - " .. id)
        assert(achv.type == 'issued' or type(achv.rank) == 'function', "Invalid field 'rank' - " .. id)

        if achv.scoreSimp == nil then
            if achv.type == 'issued' then
                achv.scoreSimp = issuedScore
            else
                achv.scoreSimp = heightFloor
                achv.scoreFull = heightNumber
            end
        end
        assert(type(achv.scoreSimp) == 'function', "Invalid field 'scoreSimp' - " .. id)
        assert(achv.scoreFull == nil or type(achv.scoreFull) == 'function', "Invalid field 'scoreFull' - " .. id)
    end
    achv.hide = achv.hide or FALSE
end
